### ISSUE TITLE
Support multiple backends for storing notes

### ISSUE THREAD

**Issue by mrdotkg** [butterops/refer#16]
The web clipper should support the following backends to store clipped contents

- [ ] #11 As a user I would like to send my web-clips to my Onenote account so that I can read them later
- [ ] #7  As a user I would like to send my web-clips to my Evernote account so that I can read them later
- [ ] #17 As a user I would like to send my web-clips to Reference app on my desktop so that I can read them later
